### ISSUE TITLE
Add prettier

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-javascript#1]
Add the prettier tool for formatting all the javascript examples in the `examples/` directory
- adding the package as devDependencies
- set in the scripts section of the package.json file the command: `npx prettier ./examples/ --write`

**Comment by dushyantpant5** [comment]
Hey @roberto-butti , could you assign me?

**Comment by roberto-butti** [comment]
> Hey @roberto-butti , could you assign me?

Of course! Thank you

**Comment by mahesha1150** [comment]
Hi @roberto-butti, I am new to Opensource. I would like to take up this issue as good first issue. Please let me know how can I contribute to this project or any pending issues. TIA

**Comment by roberto-butti** [comment]
> Hi @roberto-butti, I am new to Opensource. I would like to take up this issue as good first issue. Please let me know how can I contribute to this project or any pending issues. TIA

Hello @mahesha1150 i wrote a couple of documents about how to contribute:
- Hacktoberfest: https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- Contributing: https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md
Thank you for your interest in contributing on this project!

**Comment by roberto-butti** [comment]
> Hey @roberto-butti , could you assign me?

Thank you @dushyantpant5  for the PR #2  . It was great!
Closing this issue.

**Comment by dushyantpant5** [comment]
@roberto-butti Thank You, will always be happy to work more with you.
