### ISSUE TITLE
New Function: String concat()

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-javascript#21]
## What
Add a new method documentation file for a new JavaScript function in `src/content/docs`.
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Function name: `String.concat()`
Function description: string for concatenating strings
File name: example `src/content/docs/05-string/01_str-concat.md`

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute `bun run format-examples-bun` or `npm run format-examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

**Comment by lucasfirmo62** [comment]
Hello @roberto-butti, I would like to make this issue! Can you put me as Assignees?

**Comment by roberto-butti** [comment]
Thank you, @lucasfirmo62, for joining. Of course, I'm assigning the issue to you.

Roberto

**Comment by Shashankpantiitbhilai** [comment]
I would like to contribute to it,please assign this to me

**Comment by SD-Dev10** [comment]
Hello @roberto-butti, please assign this issue to me and allow me to contribute.

**Comment by roberto-butti** [comment]
Hi @Shashankpantiitbhilai  and @SD-Dev10  at the moment the issue was already assigned to @lucasfirmo62 .
Let's see if he needs help to complete it.
