### ISSUE TITLE
A typo on a page about checking an element in an array

### ISSUE THREAD

**Issue by ildar-faizov** [roberto-butti/some-drops-of-javascript#26]
https://drops-of-javascript.hi-folks.dev/02-array/02_array-includes/
Here the function is referenced in the 1st paragraph as `include`, although the header and the code refer to it as `includes`.

**Comment by roberto-butti** [comment]
thank you @ildar-faizov  for highlight this typo!

**Comment by Shashankpantiitbhilai** [comment]
please assign this to me.I will fix it

**Comment by Shashankpantiitbhilai** [comment]
I have submitted a pull request  please check it  @ildar-faizov

**Comment by roberto-butti** [comment]
THank you, again @ildar-faizov for finding this typo and to @Shashankpantiitbhilai for fixing it.
I'm going to close this issue thanks to the PR #27
