### ISSUE TITLE
New constant: os.EOL

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-javascript#28]
## What
Add new method documentation file for a new JavaScript function in `src/content/docs`.
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Constant name: `os.EOL`
Constant description: ...
File name: `src/content/docs/03-var/03_os-eol.md`

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute `bun run format-examples-bun` or `npm run format-examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

**Comment by mahesha1150** [comment]
Hi @roberto-butti , Can you please assign this to me.

**Comment by roberto-butti** [comment]
Of course @mahesha1150 .
Thank you for all your effort. I'm going to assign you.

Roberto

**Comment by roberto-butti** [comment]
closed by PR #31

**Comment by mahesha1150** [comment]
Hi Roberto, Can you add String.includes() as issue and assign it to me.
