### ISSUE TITLE
New Function: getOwnPropertyNames()

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-javascript#29]
## What
Add new method documentation file for a new JavaScript function in `src/content/docs`.
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Function name: `Object. getOwnPropertyNames()`
Function description: ...
File name: `src/content/docs/03-var/04_object-getOwnPropertyNames.md`

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute `bun run format-examples-bun` or `npm run format-examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

**Comment by sayumimuthu** [comment]
Hi, I'd like to work on this issue. Can you assign it to me?

**Comment by roberto-butti** [comment]
> Hi, I'd like to work on this issue. Can you assign it to me?
> 

of course @sayumimuthu , thank you for offering your support.

**Comment by roberto-butti** [comment]
Closing the issue, thanks for the pull request #37
