### ISSUE TITLE
Improving readability by changing fonts and enhancing color contrast

### ISSUE THREAD

**Issue by vipulpandey7860** [roberto-butti/some-drops-of-javascript#32]
Currently, the font used (I guess Lora) doesn't provide much readability. I propose to change to some other open-source font that would enhance readability.

Additionally, the color contrast on some text is not good, and I want to improve it.

**Comment by roberto-butti** [comment]
Thank you @I-VipulPandey, for your valuable feedback.
Do you have some suggestions? For example, which is the best open-source font that would enhance readability?
Which are the improvements we can apply to color contrast?

Happy to listen to your opinion.

Feel free to drop suggestions here, or better (if you want), open a PR.

**Comment by I-VipulPandey** [comment]
You are currently using a serif typeface (lora), which is not considered ideal for readability on digital screens. I recommend using Roboto, an open-source font widely available on various devices. Roboto is known for its excellent readability on digital screens. If you'd like, you can assign me the task, and I'll be happy to work on implementing this change.

**Comment by vipulpandey7860** [comment]
You are currently using a serif typeface (lora), which is not considered ideal for readability on digital screens. I recommend using Montserrat, an open-source font widely available on various devices. Montserrat is known for its excellent readability on digital screens. If you'd like, you can assign me the task, and I'll be happy to work on implementing this change.
