### ISSUE TITLE
Creating a new topic 'Object' mdx for: Object Methods 

### ISSUE THREAD

**Issue by SyedaMahamFahim** [roberto-butti/some-drops-of-javascript#4]
**Issue Title**: Enhance documentation by including information about objects and their essential methods.

**Issue Description**:

Hello maintainers and contributors,

I'm excited to participate in Hacktoberfest and would like to contribute to this project by enhancing the documentation. I believe that clear and comprehensive documentation is essential for the project's success and for making it more accessible to users and developers.

I would like to focus on the "Object Methods" topic, which includes the following subtopics:

1. `keys`
2. `values`
3. `entries`
4. `freeze`
5. `seal`
6. `isFrozen`
7. `isSealed`

My plan is to create detailed documentation for each of these methods, including explanations, code examples, and use cases. This will help both new and experienced contributors better understand how to work with these methods in JavaScript.

I'm open to feedback and collaboration, and I look forward to your guidance throughout the process. Please let me know if you have any specific requirements or preferences for the documentation format, style, or structure.

Thank you for considering my contribution, and I'm excited to get started!

Best regards,
Syeda Maham

**Comment by roberto-butti** [comment]
Hi @SyedaMahamFahim thank you for your proposal.
The goal of this project is to build an open-source eBook all together for learning and exploring.
Those functions/methods are very useful.
As you can see here: https://github.com/roberto-butti/some-drops-of-javascript/blob/main/list-of-functions.md , we have the list of the functions we want to document.
So, considering the topic is something for chapter 3.
So feel free to add them to the list-of-functions file, for example:

```
- [ ] 03-05 Accessing to the keys of an object: `keys()`
- [ ] 03-06 ... etc
```

Then, following these two notes:
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

You can start creating one file for each function (with the structure and naming convention described in the CONTRIBUTING).
Then, you can open a PR for each file. If you are interested in Hacktoberfest, please don't forget to tag the PR with hacktoberfest label.

Feel free to let me know if you have any questions.

**Comment by SyedaMahamFahim** [comment]
Hi @roberto-butti, thank you for reviewing my proposal. I plan to create a pull request during the month of October so that it can be counted towards Hacktoberfest.

**Comment by algoplutus1708** [comment]
Please assign this issue to me, I add the media queries !! Thank u!

**Comment by roberto-butti** [comment]
Hi @SyedaMahamFahim  , to keep track of the function you want to write, I added them to the [list of functions](https://github.com/roberto-butti/some-drops-of-javascript/blob/main/list-of-functions.md).
If you realize that the amount function will be too much, don't worry. We are here to explore, learn, and share with no pressure. Feel free to let me know if you have any issues.

**Comment by SyedaMahamFahim** [comment]
Hello @roberto-butti, I wanted to thank you for your contribution to creating tracks. Currently, I have implemented four object methods. It would be very helpful if you could review them and provide any necessary feedback. I am planning to complete the remaining work by the end of this week.

**Comment by roberto-butti** [comment]
I'm going to provide some feedback.
Thank you for all the contributions

**Comment by SyedaMahamFahim** [comment]
Hi @roberto-butti, 

I have updated all the pull requests and added use cases with code snippets. Whenever you have time, could you please review them? If there are any revisions required, feel free to add comments on the pull requests. I will make sure to review them and work on them accordingly.  For the last three topics, I will cover them as soon as I receive approval for the first four pull requests. 

Thank you so much for the amazing initiative and book.
