### ISSUE TITLE
New Function: Array splice()

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-javascript#43]
## What
Add new method documentation file for a new JavaScript function in `src/content/docs`.
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Function name: example `Array.splice()`
Function description: changes the content of an array, adding, replacing or removing elements
File name: example `02-array/13_array-splice.md`

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute `bun run format-examples-bun` or `npm run format-examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

**Comment by wdym69** [comment]
shouldn't it be 13_array-splice.md as 12 is assigned to array-reduce?

**Comment by roberto-butti** [comment]
> shouldn't it be 13_array-splice.md as 12 is assigned to array-reduce?

Exactly!
Thank you!
I edited the original issue to avoid misunderstandings.
I really appreciate it; thank you again.
