### ISSUE TITLE
New Function: reduce()

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-javascript#5]
## What
Documenting the function for reducing and array: `reduce()`.

Add a new method documentation file for a new JavaScript function in `src/content/docs`.
The instructions about defining the file's name are documented in the CONTRIBUTING.md file.

## Description
Function name: array.reduce()
Function description: reduce array 
File name: 02-array/12_array-reduce.md)

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute `bun run format-examples-bun` or `npm run format-examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

**Comment by japneetsingh035** [comment]
Hi @roberto-butti, Hope you are doing good! I would like to work on this issue. Can you please assign me this? Thanks

**Comment by roberto-butti** [comment]
Hi @japneetsingh035, and welcome! Of course, I'm going to assign it to you.
Enjoy the journey in the Hacktoberfest and in the Open Source :)

**Comment by roberto-butti** [comment]
Hello @japneetsingh035, how are you?
Let me know if you need any kind of support for this issue. If you have any doubts feel free to ask. Happy to help you.

Roberto

**Comment by mahesha1150** [comment]
Hi @roberto-butti. Can I work on this.

**Comment by mahesha1150** [comment]
Hi @roberto-butti. Can you please help with the keywords or syntax for below two issues to render in website:
01. How to add Line Breaks, Instead of continuous statements.
02. How to add Tab Spaces

**Comment by roberto-butti** [comment]
Hi @mahesha1150 for this project, we are using the amazing Starlight Astro.
Because the doc is written in Markdown you can follow:
- https://starlight.astro.build/guides/authoring-content/
- https://www.markdownguide.org/cheat-sheet/

**Comment by mahesha1150** [comment]
Thank you.

**Comment by roberto-butti** [comment]
closing this issue, thank you @mahesha1150 for the amazing support, the great PR.
