### ISSUE TITLE
New Function: array findIndex() 

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-javascript#52]
## What
Add new method documentation file for a new JavaScript function in `src/content/docs`.
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Function name: example `array.findIndex()`
Function description: Finds the index of the first element that matches a condition
File name: example `02-array/16_array-findindex.md`

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute `bun run format-examples-bun` or `npm run format-examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

**Comment by Prakhar29Sharma** [comment]
Hi @roberto-butti
I would like to work on this.

**Comment by roberto-butti** [comment]
> Hi @roberto-butti I would like to work on this.

Thank you @Prakhar29Sharma  , and welcome :)
I assigned to you the issue, In the https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md there are some suggestions about how to structure the markdown file.

**Comment by Prakhar29Sharma** [comment]
Hi @roberto-butti,

Thank you for assigning this task to me. I’ve raised a pull request and would appreciate it if you could review it. Please let me know if there are any issues or further changes required.

This is my first time contributing to open source, so any feedback is welcome!

**Comment by roberto-butti** [comment]
Hi @Prakhar29Sharma i merged your PR #56 .
Welcome to the club :)
