### ISSUE TITLE
New Function: Current directory: `process.cwd()`

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-javascript#53]
## What
Add new method documentation file for a new JavaScript function in `src/content/docs`.
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Function name: example `process.cwd()`
Function description: getting the current directory
File name: example `06-files/01_files-cwd.md`

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute `bun run format-examples-bun` or `npm run format-examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

**Comment by shahzdvp** [comment]
i would like to work on this...

**Comment by roberto-butti** [comment]
@shahzdvp of course! Thank you!

**Comment by roberto-butti** [comment]
closed with #59
