### ISSUE TITLE
New Function: accessing elements `at()`

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-javascript#54]
## What
Add new method documentation file for a new JavaScript function in `src/content/docs`.
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Function name: example `Array.at()`
Function description: accessing elements
File name: example `02-array/17_array-at.md`

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute `bun run format-examples-bun` or `npm run format-examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

**Comment by seferovich** [comment]
Hello @roberto-butti, could you assign me to this issue?

**Comment by roberto-butti** [comment]
Hi @seferovich , of course, welcome to the party :)

Here the suggestions for structuring the markdown file:
https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md#instructions-for-writing-a-markdown-file-for-a-javascript-function

Let me know if you need help.

Roberto

**Comment by roberto-butti** [comment]
Close with #57 . Thank you @seferovich

**Comment by seferovich** [comment]
You're welcome @roberto-butti !

It was nice working on this project and I am glad that I could help.
