### ISSUE TITLE
New Function: map and flat a nested array with `flatMap()`

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-javascript#55]
## What
Add new method documentation file for a new JavaScript function in `src/content/docs`.
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Function name: example `array.flatMap()`
Function description: map and flat a nested array
File name: example `02-array/18_array-flatmap.md`

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute `bun run format-examples-bun` or `npm run format-examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

**Comment by suja1956** [comment]
I'd really love to work on this.
