### ISSUE TITLE
New operator: typeof

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-javascript#6]
## What
Get variable type: `typeof`
Add new operator documentation file for a new JavaScript function in `src/content/docs`.
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Function name: `typeof`
Function description: explain the `typeof` operator, showing some context where you can use typeof, and provide some pratical examples.
File name: example `03-var/01_op-typeof.md`

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute `bun run format-examples-bun` or `npm run format-examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

**Comment by dev-shetty** [comment]
I would like to add this!
