### ISSUE TITLE
New Function: copyWithin()

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-javascript#61]
## What
Add new method documentation file for a new JavaScript function in `src/content/docs`.
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Function name: example `array.copyWithin()`
Function description: Shallow copies part of an array to another location in the same array
File name: example `02-array/19_array-copywithin.md`

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute `bun run format-examples-bun` or `npm run format-examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

**Comment by DomeT99** [comment]
Hi @roberto-butti 
If you want assign to me, I'd like to work on this!

**Comment by roberto-butti** [comment]
@DomeT99 of course! thank you

**Comment by roberto-butti** [comment]
closed by #68 , thank you @DomeT99
