### ISSUE TITLE
New Function: findLast()

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-javascript#62]
## What
Add new method documentation file for a new JavaScript function in `src/content/docs`.
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Function name: example `array.findLast()`
Function description: returns the last element in the array that satisfies the provided testing function
File name: example `02-array/20_array-findlast.md`

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute `bun run format-examples-bun` or `npm run format-examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

**Comment by harish08102004** [comment]
Hey @roberto-butti I can work on this

**Comment by roberto-butti** [comment]
of course @harish08102004 , thank you! and welcome

**Comment by harish08102004** [comment]
Hey @roberto-butti I have raised the pr please review it and merge.

**Comment by harish08102004** [comment]
If possible can you add the Level label so that it will be count for my Hacktoberfest contributions.

**Comment by roberto-butti** [comment]
Thank you @harish08102004  Closing this thank to PR #67  (i added the hacktoberfest-accepted label to the PR)
