### ISSUE TITLE
New Function: findLastIndex()

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-javascript#63]
## What
Add new method documentation file for a new JavaScript function in `src/content/docs`.
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Function name: example `array.findLastIndex()`
Function description: returns the last index of the element in the array that satisfies the provided testing function
File name: example `02-array/21_array-findlastindex.md`

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute `bun run format-examples-bun` or `npm run format-examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

**Comment by Prakhar29Sharma** [comment]
Hi @roberto-butti
I would like to work on this documentation

**Comment by roberto-butti** [comment]
@Prakhar29Sharma of course! thank you!

**Comment by roberto-butti** [comment]
closed by #66 , thanks to @Prakhar29Sharma
