### ISSUE TITLE
New Function: groupBy()

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-javascript#64]
## What
Add new method documentation file for a new JavaScript function in `src/content/docs`.
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Function name: example `array.groupBy()`
Function description: Groups elements of an array based on a function, either returning an object
File name: example `02-array/24_array-groupby.md`

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute `bun run format-examples-bun` or `npm run format-examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

**Comment by shahzdvp** [comment]
assign to me ,i'd like to work on this

**Comment by roberto-butti** [comment]
Assigned to you @shahzdvp  , thank you!

**Comment by lakshay-saini-au8** [comment]
@roberto-butti 
Looks no progress for now 
Can you assign this issue to me I can create PR with in 48hrs

**Comment by shahzdvp** [comment]
Apologies for the inconvenience. The work is in progress and the PR will be completed within 24 hours. Thank you

**Comment by roberto-butti** [comment]
Hi, thank you for all your commitment.
No worries, @shahzdvp, take your time, I appreciate quality over quantity or speed.
And @lakshay-saini-au8  i appreciate your availability. If you are interested, i 'm going to open new "feature requests", you can pick from there.

**Comment by lakshay-saini-au8** [comment]
@roberto-butti 
 

> Hi, thank you for all your commitment. No worries, @shahzdvp, take your time, I appreciate quality over quantity or speed. And @lakshay-saini-au8 i appreciate your availability. If you are interested, i 'm going to open new "feature requests", you can pick from there.

Sure please

**Comment by roberto-butti** [comment]
@shahzdvp please use the number 24 for the file, so name the markdown file for groupBy:
`02-array/24_array-groupby.md`

**Comment by shahzdvp** [comment]
Yes,I'm using the same

**Comment by shahzdvp** [comment]
is there any more issue i can work with

**Comment by roberto-butti** [comment]
closed by #80
