### ISSUE TITLE
New Function: keys()

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-javascript#65]
## What
Add new method documentation file for a new JavaScript function in `src/content/docs`.
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Function name: example `array.keys()`
Function description: Returns a new Array Iterator object that contains the keys (indices) for each index in the array
File name: example `02-array/23_array-keys.md`

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute `bun run format-examples-bun` or `npm run format-examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

**Comment by ChinoUkaegbu** [comment]
Hi, I'd like to work on this!

**Comment by roberto-butti** [comment]
Of course! Welcome @ChinoUkaegbu
