### ISSUE TITLE
New constant:  path.sep

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-javascript#7]
## What

Add new variable/constant documentation file  in `src/content/docs`.
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Function name: example `path.sep`
Function description: Provides the platform-specific path segment separator
File name: example `03-var/02_path-sep.md`

## Checklist
- [x] create the file with the proper name
- [x] create the documentation of the function
- [x] write example in `examples` directory
- [x] execute `bun run format-examples-bun` or `npm run format-examples`
- [x] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

**Comment by mahesha1150** [comment]
Hi Roberto, Can you please assign me this. And I am new to Hacktoberfest. Can you please give an example of commit message for the PR to register in Hacktoberfest. Thanks.

**Comment by roberto-butti** [comment]
> Hi Roberto, Can you please assign me this. And I am new to Hacktoberfest. Can you please give an example of commit message for the PR to register in Hacktoberfest. Thanks.

Hi @mahesha1150 , thank you for accepting this. Hacktoberfest is a great opportunity to learn and explore new things. So i think you can take a look of a PR for another function, but i think can be useful for you, to understand the "structure" : https://github.com/roberto-butti/some-drops-of-javascript/pull/8

**Comment by mahesha1150** [comment]
Thanks @roberto-butti . For helping me in my first Opensource contribution, would like to collaborate more with you in coming days.

**Comment by mahesha1150** [comment]
Hi @roberto-butti, Can you please let me know if this Repo is active and any contributions are pending, where I can assist with.

**Comment by roberto-butti** [comment]
@mahesha1150  yes of course, the repo is active!
there is a open issue:
- https://github.com/roberto-butti/some-drops-of-javascript/issues/3
- you can suggest new function to document
- you can review the english for the chapter already implemented.
- the list of function we want to cover is here: https://github.com/roberto-butti/some-drops-of-javascript/blob/main/list-of-functions.md
-

**Comment by mahesha1150** [comment]
Sure @roberto-butti 😊👍
