### ISSUE TITLE
New Function: entries()

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-javascript#72]
## What
Add a new method documentation file for a new JavaScript function in `src/content/docs.`
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Function name: example `array.entries()`
Function description: Returns a new Array Iterator object that contains key/value pairs for each index in the array
File name: example `02-array/20_arr-entries.md`

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute `bun run format-examples-bun` or `npm run format-examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

**Comment by DomeT99** [comment]
If it's not urgent, you can assign it to me.
I'll work on it when I have time 🚀

**Comment by shahzdvp** [comment]
@roberto-butti is there any more issue that i can work with

**Comment by roberto-butti** [comment]
closed by @DomeT99  with #81 

Thank you!
