### ISSUE TITLE
New Function: trimStart() and trimEnd()

### ISSUE THREAD

**Issue by roberto-butti** [roberto-butti/some-drops-of-javascript#83]
## What
Add new method documentation file for a new JavaScript function in `src/content/docs`.
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Function name: example `String.trimStart()` and `String.trimEnd()`
Function description: ...
File name: example `05-string/12_str-trimstart-trimend.md`

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute `bun run format-examples-bun` or `npm run format-examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

**Comment by AdityaJ2305** [comment]
Hey @roberto-butti I would like to work on this. Could you assign it to me ?

**Comment by roberto-butti** [comment]
> Hey @roberto-butti I would like to work on this. Could you assign it to me ? 

Thank you, assigned 🎉
